# This workflow executes several linters on changed files based on languages
# used in your code base whenever you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/github/super-linter
# https://megalinter.io/5.5.0/
# https://docs.github.com/de/actions
# https://docs.github.com/en/actions/learn-github-actions/contexts
---
name: CI

on:
  workflow_dispatch:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files
          # within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CSS: false
          VALIDATE_HTML: false
          VALIDATE_JAVASCRIPT: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # CSS_FILE_NAME: /home/runner/work/SonosGW/SonosGW/.stylelintrc
